name: "Build NixOS ISO"

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@v7
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
      - run: |
          git init
          git add flake.nix
          nix build .#nixosConfigurations.iso.config.system.build.isoImage --show-trace
          ls -l result/iso/
          mkdir mnt
          sudo mount -o loop result/iso/nixos-*.iso mnt
          ls -l mnt
          sudo umount mnt
          cd result/iso/
          split -b 2000M nixos-*.iso nixos_part_
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "result/iso/nixos_part_*"
          allowUpdates: true
          replacesArtifacts: true
          tag: iso
