name: "Build NixOS ISO"

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@V27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            trusted-public-keys = cosmic.cachix.org-1:Dya9IyXD4xdBehWjrkPv6rtxpmMdRel02smYzA85dPE=
            substituters = https://cosmic.cachix.org/ https://cache.nixos.org/
      - uses: DeterminateSystems/magic-nix-cache-action@v7
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
      - run: |
          nix build .#nixosConfigurations.iso.config.system.build.isoImage --show-trace
          ls -lhA result/iso/
          mkdir mnt
          sudo mount -o loop result/iso/nixos-*.iso mnt
          ls -lhA mnt
          sudo umount mnt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "result/iso/nixos-*.iso"
          allowUpdates: true
          replacesArtifacts: true
          tag: cosmic
